### ISSUE TITLE
Typo in recipes.py(?) and basicTests failure

### ISSUE THREAD

**Issue by thefold** [rittman/maybrain#6]
Trying to get this running for a work colleague.

On copying the maybrain/maybrain folder to site-packages and then trying to run test/basicTests.py

`$ python basicTests.py
Traceback (most recent call last):
  File "basicTests.py", line 17, in <module>
    from maybrain import recipes
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/maybrain/recipes.py", line 12, in <module>
    from plot import plotObj
ImportError: No module named plot`

Surely this should be mbplot?

Regardless of this, running basicTests.py results in the following error:

`$ python basicTests.py
red
red
green
blue
green
green
green
green
green
green
('x', 'gt', 0.5, 'x1', 'node')
('colour', 'eq', 'green', 'green', 'edge')
{'colour': 'green', 'weight': 0.60080034391699999}
('green', 'eq', 'green', True)
{'colour': 'green', 'weight': 0.203602458588}
('green', 'eq', 'green', True)
{'colour': 'green', 'weight': 0.16390494700200001}
('green', 'eq', 'green', True)
{'colour': 'green', 'weight': 0.84379894778099995}
('green', 'eq', 'green', True)
{'colour': 'green', 'weight': 0.242747996199}
('green', 'eq', 'green', True)
{'colour': 'green', 'weight': 0.63727884848299998}
('green', 'eq', 'green', True)
..E.
======================================================================
ERROR: test_loadAndPlot (__main__.TestSequenceFunctions)
load, threhsold and plot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basicTests.py", line 56, in test_loadAndPlot
    br, plt = recipes.loadAndPlot(self.fnameAdj, self.fnameCo, 0.5, opacity = 0.2)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/maybrain/recipes.py", line 50, in loadAndPlot
    plt = plotObj()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/maybrain/plot.py", line 41, in __init__
    self.startMayavi()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/maybrain/plot.py", line 55, in startMayavi
    self.mfig = mlab.figure(bgcolor = (1., 1., 1.,), fgcolor = (0., 0., 0.), engine = self.engine, size=(1500, 1500))
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/mayavi/tools/figure.py", line 68, in figure
    engine.new_scene(name=name, size=size)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/apptools/scripting/recordable.py", line 45, in _wrapper
    result = func(*args, **kw)
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/mayavi/core/engine.py", line 452, in new_scene
    viewer = self.scene_factory(**factory_kwargs)
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/mayavi/core/ui/mayavi_scene.py", line 86, in viewer_factory
    viewer = MayaviViewer()
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/tvtk/tools/ivtk.py", line 382, in __init__
    super(IVTK, self).__init__(**traits)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pyface/toolkit.py", line 124, in __init__
    raise NotImplementedError("the %s pyface backend doesn't implement %s" % (ETSConfig.toolkit, oname))
NotImplementedError: the null pyface backend doesn't implement ApplicationWindow

----------------------------------------------------------------------
Ran 4 tests in 0.005s

Python 2.7
apptools (4.4.0)
Babel (0.9.6)
cmp (2.1.0b0)
configobj (5.0.6)
cycler (0.10.0)
decorator (4.0.6)
docutils (0.11)
Easy-Lausanne (0.5)
functools32 (3.2.3-2)
Jinja2 (2.6)
MarkupSafe (0.11)
matplotlib (2.0.0b4-2053.g440adff)
mayavi (4.5.0)
mpmath (0.19)
networkx (1.11)
nibabel (2.0.2)
nipy (0.4.0)
nipype (0.7.0.gd2cbeaa-dev)
nose (1.3.0)
numpy (1.11.1)
pip (8.1.2)
pyface (5.1.0)
Pygments (2.1.3)
pyparsing (2.1.9)
python-dateutil (2.5.3)
pytz (2016.6.1)
scipy (0.17.0)
setuptools (27.2.0)
simplejson (3.2.0)
six (1.10.0)
Sphinx (1.1.3)
SQLAlchemy (0.7.9)
subprocess32 (3.2.7)
sympy (1.0)
traits (4.5.0)
traitsui (5.1.0)
virtualenv (13.1.0)
Werkzeug (0.8.3)
wheel (0.24.0)

**Comment by thefold** [comment]
OK, so I semi-solved my problem by switching over to use anaconda instead of trying to build everything which was proving to be more trouble than it's worth.

Now, after making the above change to recipes.py and running basicTests I just get the following error

`Traceback (most recent call last):
  File "basicTests.py", line 58, in test_loadAndPlot
    plt.show()
AttributeError: plotObj instance has no attribute 'show'`

I am running this via ssh with X forwarding though so that may well be the issue.

**Comment by thefold** [comment]
Copying plot.py from the base directory to the maybrain folder in site-packages has resolved the problem. If the intention is for end-users to download this module and use it by copying the maybrain/maybrain folder into site-packages then that file should be included, or the mbplot file updated.

**Comment by rittman** [comment]
Apologies, the basicTests.py file is out of date. The plotting is now taking on by mbplot.py which is in the maybrain folder. I'm pleased you're using maybrain and a bit embarrassed about the lack of proper documentation. Please do get in touch with any further issues.
