### ISSUE TITLE
module install error

### ISSUE THREAD

**Issue by wtj0906** [rittman/maybrain#8]
Hi,
When I install the module, there is an error: package directory 'maybrain/test' does not exist. Is there anything wrong?

**Comment by rittman** [comment]
Hi,

Thanks for commenting. What code are you using when you get error?

Regards,

Tim

**Comment by wtj0906** [comment]
My python version is 2.7.12. I extract the zip file to my python packages direction , like .../anaconda2/lib/python2.7/site-package,then I cd maybrain-master and use "python setup.py install", this is what it produces,
/anaconda2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/maybrain
copying maybrain/recipes.py -> build/lib/maybrain
copying maybrain/__init__.py -> build/lib/maybrain
copying maybrain/mbplot.py -> build/lib/maybrain
copying maybrain/histology.py -> build/lib/maybrain
copying maybrain/allen.py -> build/lib/maybrain
copying maybrain/braineac.py -> build/lib/maybrain
copying maybrain/extraFns.py -> build/lib/maybrain
copying maybrain/brainObjs.py -> build/lib/maybrain
error: package directory 'maybrain/test' does not exist

**Comment by mrittman** [comment]
Thanks for getting in touch. The best option for installation is just to 
copy the maybrain/maybrain folder to your python 2.7/site-packages 
folder, there's no need to use an install script.

Best,

Martyn

**Comment by wtj0906** [comment]
Thanks, @mrittman , @rittman . The problem is solved.
